p = input("Enter the power input of the System : ");
v_in = input("Enter the input voltage : ");
fsw = input("Enter the switching frequency : ");
v_out = input("Enter the required output voltage : ");
del_iL_p = input("Enter the inductor corrent ripple in percentage : ");
del_vout = input("Enter the output voltage ripple : ");
iL = p/v_in;
del_iL = iL * (del_iL_p / 100)
ini_duty = 1 - (v_in/v_out)
R_load = (v_out * v_out) / p
L = (v_in * ini_duty) / (del_iL * fsw)
C = (v_in * ini_duty) / (del_vout * (1 - ini_duty) * R_load * fsw)